---
- name: Install
  ansible.builtin.get_url:
    url: "https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage"
    dest: /usr/bin/nvim
    owner: root
    group: root
    mode: "0755"
  become: yes

- name: Create config folder
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/nvim"
    state: directory
    mode: "0755"

- name: Copy configuration files
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir}}/.config/nvim"
    src: "."
