---
- name: Font directory
  file:
    path: "{{ ansible_user_dir }}/.fonts"
    state: directory

- name: Install depdencies
  ansible.builtin.package:
    name:
      - unzip
    state: latest
  become: yes

- name: Download Meslo
  ansible.builtin.unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Meslo.zip
    dest: "{{ ansible_user_dir }}/.fonts/"
    remote_src: yes
